### ISSUE TITLE
no vst midi input version: 08Jul2018b

### ISSUE THREAD

**Issue by Eurikon** [bsp2/VeeSeeVSTRack#1]
Hi there, this version is not recognised as an instrument, in neither of the 2 dll's.
tried in Ableton/Bitwig/Reason

same result, only loads as an effect.

See https://github.com/VCVRack/Rack/issues/1021 for issue report standards and https://github.com/VCVRack/Rack/issues/730 before posting any code or terminal output.

Operating system(s):
Version of Rack if using official binary, or commit hash and branch if compiling from source:
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

**Comment by bsp2** [comment]
thanks for noticing. the latest update should fix it.

please also read the WARNING in the Downloads section carefully -- if you try to use the effect and instruments plugins in the same DAW project your DAW _will_ crash !

**Comment by CarloCattano** [comment]
I have the same problem , downloaded the files yesterday  . Its working propperlly but no midi input , even tried with virtual ports

**Comment by Eurikon** [comment]
CarloCattano what version number!? and which type: instrument of effect?

**Comment by CarloCattano** [comment]
Sorry, just found out about the renaming of the file. It's working
prefectly now in live 10 windows 10!
