### ISSUE TITLE
Bitwig 2.4 reports error after scanning plugin

### ISSUE THREAD

**Issue by koppax** [bsp2/VeeSeeVSTRack#23]
Bitwig 2.4.3 (on Windows 10) does not show veeseevstrack_instr in the list of available plugins. Instead veeseevstrack_instr (and veeseevstrack_effect) are in the list of "Plugins with errors" with the following information:

> com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not read VST plug-in metadata
64 bit plugin host reported errors: Pluginhost returned non zero exit code -1073740791
> 

In Ableton Live 10.0.6 veeseevstrack_instr is in the plugin list but as soon as I drop it on a track Ableton crashes.
The last lines in log.txt are:

> 2019-05-10T22:26:44.173741: info: MemoryUsage: V: 5.1 GB, R: 489.5 MB, P: 457.2 MB
2019-05-10T22:26:59.343743: info: VST 2.4: Going to create: veeseevstrack_instr
2019-05-10T22:26:59.351020: info: VST 2.4: DLL File Version: 
2019-05-10T22:26:59.351053: info: VST 2.4: Plugin Path: C:\Program Files\VstPlugIns\vst2_bin\veeseevstrack_instr.dll
2019-05-10T22:26:59.355674: info: VST: Vendor Version = 1000 (0x3E8)

> 

I tried several times, restarting, reinstalling etc.

**Comment by bsp2** [comment]
Just tested it in Bitwig 2.5.1 on Windows 10. Works fine.
Same in Ableton Live 10.0.6.

Maybe your computer / your graphics card is too old. Try updating the GPU drivers !

**Comment by koppax** [comment]
Solved it: veeseevstrack_instr.dll needs write permission on the vst2_bin folder.
