### ISSUE TITLE
Dbiz and Template-shared doesn't appear in Rack with Cubase 9.5.30

### ISSUE THREAD

**Issue by caecos** [bsp2/VeeSeeVSTRack#7]
Operating system(s): Windows 10 Pro

I have noticed that these two folders (C:\vst2_bin\plugins\dBiz and C:\vst2_bin\plugins\Template_shared)  have .dll (similar to the ones in the plugins folder of Rack in the standalone installation) while none of the others folders with modules for veesee have. The problem is probably there!?

**Comment by bsp2** [comment]
I don't quite understand what problem you are talking about. I already explained to you that these are not VST but VSVR plugins which are being ignored by Cubase.

I.e. these plugins are loaded by the VSVR plugin, and this works just fine in Cubase 9.5.30.

The reasons why most rack modules are statically linked with the VST are
* Plugin support is a relatively new feature
* Rack plugin DLLs are huge (in terms of file size) and converting all modules into dynamically loaded plugins would've increased the installation+download size considerably

**Comment by caecos** [comment]
I have read carefully your message about that but what I am saying is that all the plugin folders in VeeSeeVSTRack does not have dll files...except the two, and that why I have open an issue about dBiz and Template-shared...Since only those two have dll, I have thought that it was perhaps the source of the problem I experimented. As for all the others modules, they work perfectly...

**Comment by bsp2** [comment]
Yes, there are currently just two folders with (dynamically loaded) plugin.dll files (for the reasons stated above). All other modules are statically linked with the VST.

The issue you previously had with Cubase blacklisting the VST (and crashing when trying to reactivate it) was probably some Cubase glitch. Like I mentioned before, this also happened to me with another plugin -- for no good reason.

**Comment by caecos** [comment]
For the moment I have just deleted those two folders...quite happy to use Rack in a DAW and my keyboard...thx for your hard work to port Rack as a VST instrument/effect...regards...

**Comment by bsp2** [comment]
Have fun!
You may want to check out the [latest release](https://github.com/bsp2/VeeSeeVSTRack/raw/v0.6/dist/veeseevstrack_0_6_1_win64_bin-05Aug2018.7z) in case you haven't seen it, yet.
It basically improves parameter automation support in some DAWs. Cubase might be one of them.

**Comment by caecos** [comment]
I check once in a while and the VeeSee is getting better after each update...
